#!/usr/bin/env bash

source ./utils

dry="0"

for arg in "$@"; do
  if [[ "$arg" == "--dry" ]]; then
    dry="1"
    break
  fi
done

copy_dir() {
  local source_dir="$DEV_ENV_HOME/$1"
  local to="$2"
  local dir_name=$(basename "$source_dir")
  local target_dir="$to/$dir_name"

  execute mkdir -p "$to"
  execute rm -rf "$target_dir"
  execute ln -s "$source_dir" "$target_dir"
}

copy_file() {
  local src_file="$DEV_ENV_HOME/$1"
  local target_dir="$2"
  local file_name=$(basename "$src_file")
  local target_file="$target_dir/$file_name"

  execute mkdir -p "$target_dir"
  execute rm -f "$target_file"
  execute ln -s "$src_file" "$target_file"
}

# copies dir or file and creates symlink
copy_dir .config/nvim $HOME/.config
copy_dir .local/scripts $HOME/.local
copy_file .tmux.conf $HOME
copy_file .zshrc $HOME
