#!/usr/bin/env bash

source ./utils

script_dir=$(get_script_dir)
dry="0"

while [[ $# > 0 ]]; do
    if [[ "$1" == "--dry" ]]; then
        dry="1"
    fi
    shift
done

cd $script_dir
copy_dir() {
    pushd $1 > /dev/null
    to=$2
    dirs=$(find . -maxdepth 1 -mindepth 1 -type d)
    for dir in $dirs; do
        execute rm -rf $to/$dir
        execute cp -r $dir $to/$dir
    done
    popd > /dev/null
}

copy_file() {
    from=$1
    to=$2
    name=$(basename $from)
    execute rm $to/$name 
    execute cp $from $to/$name
}

copy_dir .config $HOME/.config
copy_dir .local $HOME/.local
copy_file .tmux.conf $HOME
