#!/usr/bin/env bash

log() {
  if [[ $dry == 1 ]]; then
    echo "DRY RUN: $@"
  else
    echo "$@"
  fi
}

execute() {
  log "execute $@"
  if [[ $dry == 1 ]]; then
    return
  fi
  "$@"
}

get_script_dir() {
  echo "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
}

script_dir=$(get_script_dir)
filter=""
dry=0

while [[ $# > 0 ]]; do
  if [[ $1 == "--dry" ]]; then
    dry="1"
  else
    filter="$1"
  fi
  shift
done

log "$script_dir -- $filter"

cd $script_dir

# Finds every executable file in the dotfiles directory
scripts=$(find ./installs -maxdepth 1 -mindepth 1 -perm -111 -type f)

for script in $scripts; do
  if [ -n "$filter" ] && ! echo "$script" | grep -q "$filter"; then
    log "filtering out $script"
    continue
  fi

  execute ./$script
done
