#!/usr/bin/env bash

source ./utils

script_dir=$(get_script_dir)
filter=""
dry=0

while [[ $# > 0 ]]; do
  if [[ $1 == "--dry" ]]; then
    dry="1"
  else
    filter="$1"
  fi
  shift
done

log "$script_dir -- $filter"

cd $script_dir

# Finds every executable file in the dotfiles directory
scripts=$(find ./installs -maxdepth 1 -mindepth 1 -perm -111 -type f)

for script in $scripts; do
  if echo "$scripts" | grep -qv "$filter"; then
    log "filtering out $script"
    continue
  fi

  execute ./$script
done
