#!/usr/bin/env bash

set -e

if [[ "$(uname)" != "Darwin" ]]; then
  exit 1
fi

if command -v brew >/dev/null 2>&1; then
  echo "homebrew is already installed at: $(which brew)"
  brew --version
  exit 0
fi

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

eval "$(/opt/homebrew/bin/brew shellenv)"
echo "homebrew installed successfully"
brew --version
