#!/usr/bin/env bash

update_sde_var() {
  sed -i '' 's/^SDE_REGISTRY[[:space:]]*?=[[:space:]]*.*/SDE_REGISTRY ?= '"$1"'/' Makefile
}

registry=$1

if [[ -n "$registry" ]]; then
  update_sde_var $registry
fi

DOCKER_DEFAULT_PLATFORM="linux/amd64" make build-and-push-registry
