#!/usr/bin/env bash

update_sde_var() {
  sed -i '' 's/^SDE_REGISTRY[[:space:]]*?=[[:space:]]*.*/SDE_REGISTRY ?= '"$1"'/' Makefile
}

sde_registry=$(grep "^SDE_REGISTRY" Makefile | sed -E 's/^SDE_REGISTRY[[:space:]]+\?\=[[:space:]]+//')

registry=$1

if [[ -n "$registry" ]]; then
  update_sde_var $registry
else
  registry=$sde_registry
fi

echo "Pushing to registry: $registry"

DOCKER_DEFAULT_PLATFORM="linux/amd64" make build-and-push-registry
